# This is an example mods.toml file. It contains the data relating to the loading mods.
# There are several mandatory fields (#mandatory), and many more that are optional (#optional).
# The overall format is standard TOML format, v0.5.0.
# Note that there are a couple of TOML lists in this file.
# Find more information on toml format here:  https://github.com/toml-lang/toml
# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[28,)" #mandatory (28 is current forge version)
# A URL to refer people to when problems occur with this mod
issueTrackerURL="http://my.issue.tracker/" #optional
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
# The modid of the mod
modId="aswampscurse" #mandatory
# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
version="${file.jarVersion}" #mandatory
 # A display name for the mod
displayName="A Swamp's Curse" #mandatory
# A URL to query for updates for this mod. See the JSON update specification <here>
updateJSONURL="http://myurl.me/" #optional
# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL="https://minecraft.curseforge.com/projects/aswampscurse" #optional
# A file name (in the root of the mod JAR) containing a logo for display
logoFile="aswampscurse.png" #optional
# A text field displayed in the mod UI
credits="Models, textures and ideas: VampireRedEye, Code: RedstoneTim" #optional
# A text field displayed in the mod UI
authors="VampireRedEye, RedstoneTim" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
A Swamp's Curse - a minecraft mod made for Spooky Jam 2019
A villager was struck by lightning.
Several years after becoming a witch and practicing the arts, she discovered the illagers and joined their raids. But she never really wanted to harm the villagers.
Though out of pure corruption from the swamps, a spell failed and cursed her.
Every full moon, deep in the marshes of the swamp, a witch would rise up releasing a plague which is said to doom anyone whoever got it.
Wherever she went, crops decayed and died and anyone who was bitten by her new undead ghouls would suffer the same fate and become what they feared most.
The only known way to defeat this witch was to enchant one's blade with smite or with earth's flames making her drop a talisman which is said to cure the disease."
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.aswampscurse]] #optional
    # the modid of the dependency
    modId="forge" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="[28,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"
# Here's another dependency
[[dependencies.aswampscurse]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
